### PR TITLE
style: update Flashbots relay description

### PR DESCRIPTION
**Pull request by bertmiller**
Just a small update to how the Flashbots relay is described :)

### CODE REVIEW

**Comment by Buttaa** [comment]
> Just a small update to how the Flashbots relay is described :)

hi @bertmiller 

> and maximizes profit

This applies for every relay. There is no incentive for relays to minimize the profit of each block. 
However, it's a bit cheesy by bloxroute to have "max profit" in their name, even if data suggests the opposite. Maybe re-name the flashbots relay?

**Comment by bertmiller** [comment]
¯\_(ツ)_/¯ understood, however I'm not sure that the median person reading this would immediately understand that. The only thing they do know about the Flashbots relay by looking at this is that we are OFAC compliant, which is an important data point, but not the whole picture.

Perhaps we could expand this table to include new columns, e.g.:
* Relay name
* URL
* Compliance
* MEV strategies (all, backrunning only)
* Open source relay
* Other considerations

That lets people differentiate more easily with a glance.

**Comment by remyroy** [comment]
If a strategy needs to sandwich a transaction from an OFAC restricted wallet to maximize profit but can't be used because such a transaction cannot be included, can we say that the relay is maximizing profits?

Description and notes and are somewhat subjective at this point. If Flashbots wants to offer different relays with different ethical or censorship property, maybe we could say that one of these choices is trying to maximize profits in relation to the other offerings which I think is what bloXroute is doing here.

I would love to expand these tables with all the possible details we can gather. Our communication channels with relay operators is almost non-existant at this point. We will try to work on that last part.

**Comment by bertmiller** [comment]
> I would love to expand these tables with all the possible details we can gather. Our communication channels with relay operators is almost non-existant at this point. We will try to work on that last part.

Flashbots/I am very happy to help you with that. We really appreciate in general your work to support solo staking and mev-boost in general  ❤️  We can also help with a first pass on a table if you think that's a good idea, and then ask relay operators to confirm if the details are correct. I feel all the data needed for the categories I laid out are public.

> If a strategy needs to sandwich a transaction from an OFAC restricted wallet to maximize profit but can't be used because such a transaction cannot be included, can we say that the relay is maximizing profits?

This is fair, although we are maximizing profits within the constraints of our compliance. It is true that a OFAC censoring block might lose out to a non-OFAC censoring block.

The subjective here is what I want to avoid, though. There is subjectivity in the current descriptions and names of relays. So it is my preferences that we arm validators with as many data points as we can, and let them make a decision on what they care about.

**Comment by remyroy** [comment]
@bertmiller If you want to help us on starting this new table, we would gladly take all the help you can give us. In terms of columns, here is what I would like:

- Operator (with main link to operator relay's documentation)
- Filtering/Censorship/Compliance
- MEV Strategies/Ethical considerations
- Relay software (with link to Github project/fork if open source)
- Profit sharing model (how much of the profit goes to the validator, the relay, the builder and the searcher)
- Builders and searchers behind the relay
- Notes
- Support (Discord, Email, Telegram, others)
- Relay URL (with public key)

For most of these column, it would be nice to have a link to an official statement or a section in the operator's official documentation. Something that can be easily referenced and examined by a validator.

Let us know if this makes sense.

**Pull request closed without merging**
